CREATE DATABASE todoapp;

CREATE TABLE todo(
    TODO_ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATE_DATE TIMESTAMP DEFAULT NOW(),
    DUE_DATE VARCHAR(255),
    DONE BOOLEAN DEFAULT FALSE
);