CREATE DATABASE todoapp;

CREATE TABLE todo(
    TODO_ID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    CREATE_DATE TIMESTAMP DEFAULT NOW(),
    DUE_DATE DATE,
    DONE BOOLEAN DEFAULT FALSE
);